# Generated by Django 4.1.7 on 2023-03-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='doctor_courses',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='student_course',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_courses',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='reg_app.courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_course',
            field=models.ManyToManyField(to='reg_app.courses'),
        ),
    ]
