# Generated by Django 4.1.7 on 2023-03-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0003_remove_doctor_doctor_courses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department00',
            new_name='department',
        ),
    ]
