# Generated by Django 4.1.7 on 2023-03-26 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0005_rename_department_user_department00'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='student_course',
            field=models.ManyToManyField(related_name='students_in_course', to='reg_app.student'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_dep', to='reg_app.department'),
        ),
    ]
